name: Deploy With Terraform
run-name: Deploy With Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

jobs:
  zip-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip Folder
        working-directory: ./Backend
        run: zip ../terraform/getVisitorCount.zip getVisitorCount.py
      - name: Commit New Handler Code
        env:
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "${{ env.LOGIN_EMAIL }}"

          git add -A
          git commit -m "Zipping file via github actions"
          git push

  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      region: "us-east-1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        working-directory: ./terraform
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        working-directory: ./terraform
        if: steps.terraform-plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
    needs: zip-handler
