name: Tests
run-name: Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - Deploy With Terraform
    types:
      - complete

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: setup Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./Backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Python Backend Test
        working-directory: ./Backend
        run: python test_get_visitor_count.py
  front-end-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: setup Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./Backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Python Backend Test
        working-directory: ./Backend
        run: python test_api.py